<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo (http://webpages.charter.net/edreamleo/front.html) -->
<?xml-stylesheet ekr_test?>
<leo_file xmlns:leo="http://www.leo-editor.org/2011/leo" >
<leo_header file_format="2"/>
<vnodes>
<v t="gcross.20100923124124.1297"><vh>@chapters</vh></v>
<v t="gmc.20080805172037.20"><vh>@thin time_evolution_transverse_ising.py</vh></v>
</vnodes>
<tnodes>
<t tx="gcross.20100923124124.1297"></t>
</tnodes>
</leo_file>
